Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'FsCu\xa1y\x9b#'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'\xd0\xf3A\x90\xfe\xb2*p'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'FsCu\xa1y\x9b#'
