Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'\x05C\xc2\xb9\xf3\x04\xc4\x03'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'\x05C\xc2\xb9\xf3\x04\xc4\x03'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'C\xc3P\xc5\xc4\x1a\x82\xe9'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'C\xc3P\xc5\xc4\x1a\x82\xe9'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'C\xc3P\xc5\xc4\x1a\x82\xe9'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'C\xc3P\xc5\xc4\x1a\x82\xe9'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b'C\xc3P\xc5\xc4\x1a\x82\xe9'
Traceback (most recent call last):
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\defaultprotocol.py", line 51, in call_callback
    self.callback(addr,data)
  File "D:\Games\PyDec\DecCom-Python\deccom\protocols\peerdiscovery\kademliadiscovery.py", line 191, in process_datagram
    msg += self.finders[unique_id].look_for
KeyError: b']\xa2\x07\x8eu\xa9\xd8R'
